# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-09-03 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200829_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cv',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='post',
            name='pv',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
